product_module.message:
  path: '/thank-you'
  defaults:
    _controller: '\Drupal\product_module\Controller\ProductModuleController::build'
    _title: 'Thank You'
  requirements:
    _permission: 'product access'
